### PR TITLE
job opening for vedlogic

### PR DESCRIPTION
**Pull request by MadDevMax**
- added job opening for vedlogic

### CODE REVIEW

**Comment by MadDevMax** [comment]
Hi @JaldeepAsodariya 
Could you please review it.

**Comment by JaldeepAsodariya** [comment]
@MadDevMax Please please please
Read the contribution guideline carefully
Step no. 5: Raise a PR to `develop` branch
 https://github.com/GDGAhmedabad/devfestahm#list-job-opportunities-of-the-companies

**Comment by MadDevMax** [comment]
Hi @JaldeepAsodariya 
I have changed branch from main to develop
Sorry for the troubles 
Thanks,

**Comment by JaldeepAsodariya** [comment]
Thank You.
Will merge it by tomorrow.

**Review by JaldeepAsodariya — APPROVED** [review]

**Pull request merged**
