### PR TITLE
Added Devapps current openings

### PR DESCRIPTION
**Pull request by liyamahendra**
@JaldeepAsodariya kindly review this PR when you can. Thank you!

### CODE REVIEW

**Comment by liyamahendra** [comment]
@PareshMayani kindly review this PR and do the needful. Thanks!

**Comment by JaldeepAsodariya** [comment]
Added your openings manually a2bdd4bf970ba10e899ff7f8a12322a2a33f12ab
Thanks

**Comment by liyamahendra** [comment]
@JaldeepAsodariya that's very kind of you! But I don't see the openings on the site. Are the changes deployed? 

screencapture-devfest-gdgahmedabad-job-openings-2022-12-20-17_30_16

**Comment by JaldeepAsodariya** [comment]
We will deploy in prod very soon.

**Pull request closed without merging**
