### PR TITLE
[Fix] [Speaker] Social Links

### PR DESCRIPTION
**Pull request by piedcipher**
Twitter & Medium links of [Bhoomi](https://devfest.gdgahmedabad.com/speakers/bhoomi_vaghasiya) are showing 404, might have been changed by her.

Twitter link of [Madhu Vadlamani](https://devfest.gdgahmedabad.com/speakers/madhu_vadlamani) is showing 404.

I was browsing the DevFestAhm site and came across it. I've fixed this issue by correcting links.

### CODE REVIEW

**Comment by JaldeepAsodariya** [comment]
Hey @piedcipher 
bhoomi_vaghasiya social changes received in #284 

Can you please update with develop upstream and send only Madhu's changes?

**Comment by piedcipher** [comment]
> Hey @piedcipher bhoomi_vaghasiya social changes received in #284
> 
> Can you please update with develop upstream and send only Madhu's changes?

Sure

**Comment by piedcipher** [comment]
> Hey @piedcipher bhoomi_vaghasiya social changes received in #284
> 
> Can you please update with develop upstream and send only Madhu's changes?

Done 👍✅ I've rebased my branch with upstream's develop.

**Comment by JaldeepAsodariya** [comment]
It's showing both PR changes.

**Comment by piedcipher** [comment]
I think that's because me and Deep made changes on same line. I rebased properly though. No worries let me send a fresh pr.

**Pull request closed without merging**
