### PR TITLE
[Speaker] [Socials]  Twitter for harsh_goyal speaker

### PR DESCRIPTION
**Pull request by piedcipher**
Added Twitter of harsh_goyal speaker.

### CODE REVIEW

**Comment by JaldeepAsodariya** [comment]
Have you asked to the speaker for this?

**Comment by piedcipher** [comment]
> Have you asked to the speaker for this?

Yes I've asked him. He's fine with it. Took his permission first before raising pr. You can also check once.

**Comment by piedcipher** [comment]
Screenshot_20231215-010528

He's is my friend. I asked him via WhatsApp.

**Comment by JaldeepAsodariya** [comment]
Ok Great, Thanks for prior confirmation.
Because we haven't received from him so not added :)

**Review by JaldeepAsodariya — APPROVED** [review]

**Pull request merged**
